name:                domain-driven
version:             0.1.0.0
github:              "tommyengstrom/domain-driven"
license:             BSD3
author:              "Tommy Engström"
maintainer:          "tommy@tommyengstrom.com"
copyright:           "2021 Tommy Engström"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tommyengstrom/domain-driven#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- async
- bytestring
- containers
- deepseq
- directory
- exceptions
- generic-lens
- lens
- monad-loops
- mtl
- openapi3
- postgresql-simple
- random
- safe
- servant
- servant-server
- stm
- streaming
- template-haskell
- text
- time
- transformers
- vector
- streamly
- unordered-containers
- uuid
- unliftio

default-extensions:
- Arrows
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FunctionalDependencies
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- PolyKinds
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedLabels
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilyDependencies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

library:
  source-dirs: src
  dependencies:
    - http-types

tests:
  domain-driven-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -ddump-splices
    dependencies:
    - domain-driven
    - hspec
    - hspec-core
    - QuickCheck
    - quickcheck-classes
    - quickcheck-arbitrary-adt
    - async
    - servant-client
    - servant-openapi3
    - warp
    - http-client

executables:
  simple:
    main:                Main.hs
    source-dirs:         examples/simple
    dependencies:
    - domain-driven
    - wai
    - servant-openapi3
    - warp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -ddump-splices
