resolver: lts-24.12
packages:
- domaindriven-core
- domaindriven-effectful
- domaindriven-effectful-examples

extra-deps:
  
ghc-options:
  "$locals": -fwrite-ide-info
  '$everything': -haddock
    -hiedir=.hie

allow-newer: true
allow-newer-deps:
  - openapi3
  - servant-auth-server
  - servant-openapi3
  - insert-ordered-containers

system-ghc: true
