name:                domaindriven-effectful
version:             0.5.0
github:              "tommyengstrom/domaindriven"
license:             BSD3
author:              "Tommy Engström"
maintainer:          "tommy@tommyengstrom.com"
copyright:           "2023 Tommy Engström"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Batteries included event sourcing and CQRS
category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tommyengstrom/domaindriven#readme>

dependencies:
- base
- effectful
- effectful-th
- aeson
- domaindriven-core
- exceptions
- generics-sop
- openapi3
- optics
- servant
- servant-auth-server
- servant-client-core
- servant-openapi3
- servant-server
- text


default-extensions:
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- StrictData
- TupleSections
- TypeApplications
- TypeFamilyDependencies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

ghc-options:
- -Weverything
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wincomplete-record-updates
- -Wincomplete-patterns
- -Wno-unused-packages

library:
  source-dirs: src
  dependencies:
    - bytestring
    - mtl
    - unliftio
    - uuid
