name:                domaindriven
version:             0.5.0
github:              "tommyengstrom/domaindriven"
license:             BSD3
author:              "Tommy Engström"
maintainer:          "tommy@tommyengstrom.com"
copyright:           "2023 Tommy Engström"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Batteries included event sourcing and CQRS
category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tommyengstrom/domaindriven#readme>

dependencies:
- aeson >= 2.0.3 && < 2.2
- base >= 4.7 && < 5
- containers >= 0.6.5.1 && < 0.7
- deepseq >= 1.4.6.1 && < 1.5
- exceptions >= 0.10.4 && < 0.11
- openapi3 >= 3.2.2 && < 3.3
- servant-server >= 0.19.2 && < 0.20
- servant-client-core
- servant >= 0.19.1 && < 0.20
- text >= 1.2.5.0 && < 1.3
- domaindriven-core >= 0.5.0 && < 0.6
- generics-sop
- constraints
- servant-openapi3
- optics
- servant-auth-server


default-extensions:
- Arrows
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilyDependencies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -Wincomplete-record-updates
- -Wincomplete-patterns

library:
  source-dirs: src
  dependencies:
    - random >= 1.2.1.1 && < 1.3
    - http-types >= 0.12.3 && < 0.13
    - bytestring >= 0.11.3 && < 0.12
    - template-haskell >= 2.18.0.0 && <2.19
    - transformers >=  0.5.6.2 && < 0.6
    - unordered-containers >= 0.2.19.1 && <0.3
    - vector >= 0.12.3.1 && <0.13
    - unliftio >= 0.2.0.1 && <0.3
    - streamly >= 0.8.1.1 && <0.9
    - postgresql-simple >= 0.6.4 && <0.7
    - async >= 2.2.4 && <2.3
    - generic-lens >= 2.2.1.0 && <2.3
    - microlens >= 0.4.12.0 && <0.5
    - time >=  1.11.1.1 && < 1.12
    - unliftio-pool >= 0.2.2.0 && <0.3
    - uuid >= 1.3.15 && <1.4
    - mtl >= 2.2.2 && <2.3

tests:
  domaindriven-test:
    main:                Spec.hs
    source-dirs:
      - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wunused-packages
    dependencies:
    - domaindriven >= 0.5.0 && < 0.6
    - hspec >= 2.9.7 && <2.10
    - QuickCheck >= 2.14.2 && <2.15
    - quickcheck-arbitrary-adt >= 0.3.1.0 && <0.4
    - quickcheck-classes >= 0.6.5.0 && <0.7
    - warp >= 3.3.23 && <3.4
    - servant-client >= 0.19 && <0.20
    - async >= 2.2.4 && < 2.3
    - mtl >= 2.2.2 && < 2.3
    - http-client >= 0.7.13.1 && <0.8
